
title: The Spoken Abstracts Project
page-top-title: Spoken Abstracts
top-section-bg-text: Spoken Abstracts
home-subtitle: Beyond Text: Amplify Your Impact with Spoken Abstracts.
copyright-text: '&copy; John James 2024. All Rights Reserved.'
