
title: The Spoken Abstracts Project
page-top-title: Spoken Abstracts
top-section-bg-text: Computer Science
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Sen Li 2023. All Rights Reserved.'
